import { pythonRelationshipInventory, completeSupportedRelationships, reconcileArchitectureRows } from '../code-architecture-context/codeRelationshipEvidence';
import { ensureCodeArchitectureTraceIds, buildCodeArchitectureHazardInput } from '../code-architecture-hazard-analysis/codeArchitectureHazardUtils';
import { deriveSoftwareRequirements, deriveSystemRequirements, deriveSubsystemRequirements, deriveDesignElements } from './artifactAI';
import { saveArtifactRowsAsync, loadArtifactRowsAsync, architectureRefFromFunctionalRow, functionalRowIndexForTraceValue } from './artifactUtils';
import { buildTraceabilityRows } from './TraceabilityMatrixPanel';
import { resolveArchitectureTarget } from '../../components/codeArchitectureNavigation';
import { buildImpactFileContexts, buildSourceSnippetsForPatch } from '../safety-remediation/safetyRemediationSourceContext';
import { ARTIFACT_KINDS } from './artifactDefinitions';
import { codeReferencesFromEvidence, architectureElementFromRow } from '../safety-remediation/safetyRemediationUtils';
import { generateSafetyFindingsFromArchitectureElement } from '../safety-remediation/safetyRemediationAI';
import { safetyRemediationStore } from '../safety-remediation/safetyRemediationStore';
jest.mock('lucide-react', () => new Proxy({}, { get: () => () => null }));
jest.mock('../../components/backendConfig',()=>({backendURL:'https://fixture.test',buildAuthOpts:()=>({headers:{}}),buildAIAuthOpts:()=>({headers:{}})}));
const fixture=()=>ensureCodeArchitectureTraceIds(reconcileArchitectureRows(completeSupportedRelationships([],pythonRelationshipInventory('control.py','def validate_command():\n    pass\ndef control_motion():\n    validate_command()')),[],'project:p:repo'));
const response=value=>Promise.resolve({ok:true,json:async()=>({answer:JSON.stringify(value)})});
beforeEach(()=>{localStorage.clear();jest.spyOn(console,'log').mockImplementation(()=>{});jest.spyOn(console,'warn').mockImplementation(()=>{});});
afterEach(()=>jest.restoreAllMocks());
it('preserves the six-area chain through reordered reruns, edits, save/reload and JSON restoration',async()=>{
 const original=fixture(), trace=original[0].traceId;
 global.fetch=jest.fn(async(url,options)=>{
   const payload=JSON.parse(JSON.parse(options.body).messages[1].content),task=payload.task;
   if(task.includes('categorize_')||task.startsWith('review_')) return response({categories:[{id:'CAT-1',categoryName:'Protective control',requirementIntent:'Keep vehicle commands within accepted bounds',parentSwRequirement:'SWR-1',parentSystemRequirement:'SYS-1',parentRequirement:'SUB-1',subsystem:'Control'}]});
   if(task.includes('derive_software_')) return response({requirements:[{id:'SWR-1',sourceTraceId:trace,requirementText:'The software shall reject invalid motion requests before actuation.',verificationMethod:'Test'}]});
   if(task.includes('derive_system_requirements_')) return response({requirements:[{id:'SYS-1',parentSwRequirement:'SWR-1',requirementText:'The system shall constrain vehicle motion to the authorized operating envelope.',verificationMethod:'Test'}]});
   if(task.includes('derive_subsystem_requirements_')) return response({requirements:[{id:'SUB-1',parentSystemRequirement:'SYS-1',subsystem:'Control',requirementText:'The Control subsystem shall block requests outside the permitted command limits.',verificationMethod:'Test'}]});
   if(task.includes('derive_system_subsystem_design_')) return response({designElements:[{id:'DES-1',parentRequirement:'SUB-1',designElementName:'Command Validator',description:'The command validator checks permitted motion bounds and blocks requests that exceed them.',subsystem:'Control'}]});
   throw new Error(`Unexpected fixture AI task ${task}`);
 });
 const hazard=buildCodeArchitectureHazardInput({cbaRows:original,projectId:'p',repoMeta:{repoId:'fixture/repo'},operationalContexts:[{id:'curb',scenario:'Curbside',mode:'Remote driving'},{id:'depot',scenario:'Depot',mode:'Remote driving'}]});
 expect(hazard.tableRows.length).toBeGreaterThan(1);
 expect(new Set(hazard.tableRows.map(row=>row.operationalContextId)).size).toBe(2);
 expect(hazard.tableRows.every(row=>row.traceId===trace)).toBe(true);
 const sw=await deriveSoftwareRequirements({cbaRows:original});
 const sys=await deriveSystemRequirements({softwareRequirements:sw});
 const sub=await deriveSubsystemRequirements({systemRequirements:sys});
 const design=await deriveDesignElements({subsystemRequirements:sub});
 expect([sw,sys,sub,design].every(rows=>rows.length>0)).toBe(true);
 expect(sw[0].sourceTraceId).toBe(trace);
 sw[0].requirementText='Manually reviewed requirement';sw[0].reviewStatus='approved';
 const data={cbaRows:original,softwareRows:sw,systemRows:sys,subsystemRows:sub,designRows:design};
 const matrix=buildTraceabilityRows(data);
 expect(matrix.some(row=>row.softwareRequirement.includes(sw[0].id)&&row.traceCompleteness==='Complete')).toBe(true);
 const updated=ensureCodeArchitectureTraceIds(reconcileArchitectureRows([...original].reverse(),original,'project:p:repo'));
 expect(updated[0].traceId).toBe(trace);
 for(const [kind,rows] of [[ARTIFACT_KINDS.SOFTWARE,sw],[ARTIFACT_KINDS.SYSTEM,sys],[ARTIFACT_KINDS.SUBSYSTEM,sub],[ARTIFACT_KINDS.DESIGN,design]]) {
   await saveArtifactRowsAsync(kind,'p','repo',rows);
   expect(await loadArtifactRowsAsync(kind,'p','repo')).toEqual(rows);
 }
 const restored=JSON.parse(JSON.stringify({...data,cbaRows:updated}));
 expect(restored.softwareRows[0]).toMatchObject({requirementText:'Manually reviewed requirement',reviewStatus:'approved'});
 expect(buildTraceabilityRows(restored)).toEqual(matrix);
 expect(resolveArchitectureTarget(architectureRefFromFunctionalRow(original[0]),restored.cbaRows).traceId).toBe(trace);
 const history=updated.map(row=>({...row,lineage:{...row.lineage,status:'historical'}}));
 expect(buildCodeArchitectureHazardInput({cbaRows:history}).tableRows).toHaveLength(0);
 expect(buildTraceabilityRows({...data,cbaRows:history}).every(row=>row.traceCompleteness!=='Complete')).toBe(true);
 expect(resolveArchitectureTarget({traceId:trace},history).resolutionStatus).toBe('historical');
 expect(resolveArchitectureTarget({traceId:'missing',row:original[0]},updated)).toBeNull();
 expect(functionalRowIndexForTraceValue([...updated,updated[0]],trace)).toBe(-1);
 expect(functionalRowIndexForTraceValue(updated,String(updated[0].rowRef))).toBe(0);
 expect(buildTraceabilityRows({...data,cbaRows:[]})[0].openIssues).toMatch(/architecture evidence/);
});
it('does not substitute the active workspace for retained GitHub snapshot evidence',async()=>{
 global.fetch=jest.fn(()=>{throw new Error('No live workspace or remote fallback allowed');});
 const result=await buildImpactFileContexts({codeReferences:[{sourceType:'github',evidenceVersion:1,snapshotId:'a'.repeat(40),filePath:'control.py',content:'def historical_control(): pass'}],repoMeta:{owner:'fixture',repo:'repo',branch:'changed'}});
 expect(JSON.stringify(result)).toContain('historical_control');expect(fetch).not.toHaveBeenCalled();
});
it('preserves hazard-derived remediation evidence, edits and review through save/reload', async () => {
 const provenance={sourceType:'github',evidenceVersion:1,snapshotId:'a'.repeat(40)};
 const row={...fixture()[0],...provenance,sourceEvidence:{functions:[{filePath:'control.py',functionName:'validate_command',content:'def validate_command(): pass',startLine:1,endLine:1}]}};
 const element=architectureElementFromRow(row);
 const refs=codeReferencesFromEvidence({architectureElement:element,repoMeta:{owner:'fixture',repo:'repo'}});
 expect(refs[0]).toMatchObject({...provenance,content:'def validate_command(): pass'});
 const legacyRefs=codeReferencesFromEvidence({architectureElement:{row:{fromFile:'old.py'}},repoMeta:provenance});
 expect(legacyRefs[0]).not.toHaveProperty('snapshotId');
 const hazard={id:'hazard-1',hazardRowRef:'RAW-1',architectureRowRef:row.rowRef,architectureElementId:element.id,Hazards:'The vehicle moves with an invalid command while pedestrians are exposed.',affectedCodeRefs:refs};
 global.fetch=jest.fn(async()=>({ok:true,json:async()=>({result:JSON.stringify([{id:'finding-1',title:'Invalid command acceptance',description:'The validator permits an invalid motion command to reach actuation.',hazard:hazard.Hazards,causalFactor:'Missing bounds check on a motion request',proposedMitigation:'Check bounds before issuing the request.',hazardRowRef:'RAW-1'}])})}));
 const findings=await generateSafetyFindingsFromArchitectureElement({element,hazardSummaryRows:[hazard],hazardAnalysis:{id:'run-1',summaryRows:[hazard]},project:{id:'p'},repoMeta:{repoId:'fixture/repo'}});
 expect(findings.length).toBeGreaterThan(0);
 expect(fetch).toHaveBeenCalledTimes(1);
 expect(findings[0].affectedCodeRefs[0]).toMatchObject(provenance);
 findings[0].proposedMitigation='Human-reviewed mitigation';findings[0].reviewStatus='approved';
 await safetyRemediationStore.upsertFindings(findings);
 const stored=await safetyRemediationStore.loadFindings();
 expect(stored.find(item=>item.id===findings[0].id)).toMatchObject({proposedMitigation:'Human-reviewed mitigation',reviewStatus:'approved'});
 const restored=JSON.parse(JSON.stringify(stored));
 expect(restored[0].affectedCodeRefs[0]).toMatchObject(provenance);
});
it('keeps same-path snapshots separate and retains original embedded excerpt line numbers', async () => {
 global.fetch=jest.fn(()=>{throw new Error('No remote fallback allowed');});
 const refs=['a','b'].map(revision=>({sourceType:'github',evidenceVersion:1,snapshotId:revision.repeat(40),filePath:'control.py',symbolName:'validate',startLine:100,endLine:100,contentStartLine:100,content:`def validate(): return '${revision}'`}));
 const snippets=await buildSourceSnippetsForPatch({codeReferences:refs});
 expect(snippets).toHaveLength(2);
 expect(snippets.every(snippet=>snippet.content.includes('100 | def validate'))).toBe(true);
 const contexts=await buildImpactFileContexts({codeReferences:refs});
 expect(contexts).toHaveLength(2);
 expect(contexts[0].references).toHaveLength(1);
 expect(fetch).not.toHaveBeenCalled();
});
