export const DIAGRAM_NODE_PROVENANCE = Object.freeze({
  GENERATED: 'functional-row',
  MANUAL: 'user-manual',
  NOTE: 'user-note',
});

export function getDiagramNodeProvenance(node) {
  const explicit = node?.data?.provenance || node?.provenance;
  if (explicit) return explicit;
  if (node?.type === 'note' || String(node?.id || '').startsWith('note:')) {
    return DIAGRAM_NODE_PROVENANCE.NOTE;
  }
  if (/^n:new:\s*\d+$/i.test(String(node?.id || '').trim())) {
    return DIAGRAM_NODE_PROVENANCE.MANUAL;
  }
  return null;
}

export function withDiagramNodeProvenance(node, provenance) {
  return {
    ...node,
    data: { ...(node?.data || {}), provenance },
  };
}

export function buildFunctionSubsystemOwnershipMap(rows = [], normalizeSubsystem = (value) => String(value || '').trim()) {
  const countsByFunction = new Map();
  (rows || []).forEach((row) => {
    const subsystem = normalizeSubsystem(row?.subsystem || '');
    const fromFunction = String(row?.fromFunction || '').trim();
    if (!subsystem || !fromFunction || /\b(unallocated|unassigned|uncategorized)\b/i.test(subsystem)) return;
    const functionKey = fromFunction.toLowerCase();
    const counts = countsByFunction.get(functionKey) || new Map();
    counts.set(subsystem, (counts.get(subsystem) || 0) + 1);
    countsByFunction.set(functionKey, counts);
  });

  const ownership = new Map();
  countsByFunction.forEach((counts, functionKey) => {
    const ranked = Array.from(counts.entries()).sort((a, b) => b[1] - a[1]);
    if (ranked[0]?.[0]) ownership.set(functionKey, ranked[0][0]);
  });

  // A receiver-only leaf has no source row from which to infer ownership. Use
  // the interface row's subsystem, matching the table-category allocator.
  (rows || []).forEach((row) => {
    const subsystem = normalizeSubsystem(row?.subsystem || '');
    const toFunction = String(row?.toFunction || '').trim();
    if (!subsystem || !toFunction || /\b(unallocated|unassigned|uncategorized)\b/i.test(subsystem)) return;
    const functionKey = toFunction.toLowerCase();
    if (!ownership.has(functionKey)) ownership.set(functionKey, subsystem);
  });

  return ownership;
}

export function isLegacyGeneratedContainerArtifact(node, autoGroupBoxes = []) {
  if (!node || node.type === 'note') return false;
  if (getDiagramNodeProvenance(node) === DIAGRAM_NODE_PROVENANCE.GENERATED) return true;
  if (getDiagramNodeProvenance(node)) return false;
  const rawLabel = String(node?.data?.label || '').trim();
  const label = rawLabel.toLowerCase();
  if (!label) return false;
  const canonicalNodeId = `n:${rawLabel}`.toLowerCase();
  return autoGroupBoxes.some((box) => (
    box?.autoGenerated &&
    String(box.label || '').trim().toLowerCase() === label &&
    String(node.id || '').trim().toLowerCase() === canonicalNodeId
  ));
}

export function reconcileStoredManualNodes({ manualNodes = [], wantedNodeIds = new Set(), autoGroupBoxes = [] }) {
  const kept = [];
  const prunedIds = new Set();
  for (const node of manualNodes || []) {
    const provenance = getDiagramNodeProvenance(node);
    const isWanted = wantedNodeIds.has(node?.id);
    const generated = provenance === DIAGRAM_NODE_PROVENANCE.GENERATED ||
      isLegacyGeneratedContainerArtifact(node, autoGroupBoxes);
    if (generated) {
      // A current endpoint is rebuilt from rows. A former endpoint is discarded.
      prunedIds.add(node.id);
      continue;
    }
    if (isWanted && !provenance) {
      // Legacy ambiguity is preserved; the row renderer owns the visible copy.
      kept.push(node);
      continue;
    }
    kept.push(node);
  }
  return { manualNodes: kept, prunedIds };
}

export function resolveGeneratedNodePlacement({
  saved,
  existing,
  expectedGroup,
  groupById = new Map(),
  explicitlyUngrouped = false,
}) {
  const savedParent = saved?.parentId && groupById.has(saved.parentId) ? saved.parentId : null;
  const explicitParent = saved?.groupingIntent === 'explicit' && savedParent;
  const parentId = explicitlyUngrouped ? null : (explicitParent || expectedGroup?.id || null);
  const oldParent = existing?.parentNode ? groupById.get(existing.parentNode) : (savedParent ? groupById.get(savedParent) : null);
  const local = saved?.position || existing?.position;
  const absolute = local
    ? (oldParent ? { x: oldParent.position.x + local.x, y: oldParent.position.y + local.y } : { ...local })
    : null;
  const position = absolute && parentId
    ? { x: absolute.x - groupById.get(parentId).position.x, y: absolute.y - groupById.get(parentId).position.y }
    : absolute;
  return { parentId, position, groupingIntent: explicitParent ? 'explicit' : 'automatic' };
}
