import {
  buildFunctionSubsystemOwnershipMap,
  DIAGRAM_NODE_PROVENANCE,
  reconcileStoredManualNodes,
  resolveGeneratedNodePlacement,
  withDiagramNodeProvenance,
} from './functionalDiagramNodeReconciliation';

const groupA = { id: 'g:a', label: 'A', position: { x: 100, y: 100 }, autoGenerated: true };
const groupB = { id: 'g:b', label: 'B', position: { x: 500, y: 100 }, autoGenerated: true };

test('receiver-only functions use the same fallback ownership as subsystem categories', () => {
  const ownership = buildFunctionSubsystemOwnershipMap([
    { subsystem: 'Planning', fromFunction: 'Plan Route', toFunction: 'Execute Motion' },
    { subsystem: 'Control', fromFunction: 'Execute Motion', toFunction: 'Report Status' },
  ]);
  expect(ownership.get('plan route')).toBe('Planning');
  expect(ownership.get('execute motion')).toBe('Control');
  expect(ownership.get('report status')).toBe('Control');
});

test('removed or renamed generated endpoints are pruned while manual nodes and notes survive', () => {
  const generated = withDiagramNodeProvenance({ id: 'n:Old', data: { label: 'Old' } }, DIAGRAM_NODE_PROVENANCE.GENERATED);
  const manual = withDiagramNodeProvenance({ id: 'n:new: 1', data: { label: 'Mine' } }, DIAGRAM_NODE_PROVENANCE.MANUAL);
  const note = withDiagramNodeProvenance({ id: 'note:1', type: 'note', data: { label: 'Note' } }, DIAGRAM_NODE_PROVENANCE.NOTE);
  const result = reconcileStoredManualNodes({ manualNodes: [generated, manual, note], wantedNodeIds: new Set(['n:New']) });
  expect(result.manualNodes.map((node) => node.id)).toEqual(['n:new: 1', 'note:1']);
  expect(result.prunedIds).toEqual(new Set(['n:Old']));
});

test('ownership change reparents only the affected generated node at the same absolute position', () => {
  const groups = new Map([[groupA.id, groupA], [groupB.id, groupB]]);
  const moved = resolveGeneratedNodePlacement({ saved: { position: { x: 30, y: 40 }, parentId: groupA.id }, expectedGroup: groupB, groupById: groups });
  const unrelated = resolveGeneratedNodePlacement({ saved: { position: { x: 60, y: 70 }, parentId: groupA.id }, expectedGroup: groupA, groupById: groups });
  expect(moved).toMatchObject({ parentId: groupB.id, position: { x: -370, y: 40 } });
  expect(unrelated).toMatchObject({ parentId: groupA.id, position: { x: 60, y: 70 } });
});

test('explicit ungroup and regroup decisions override automatic ownership', () => {
  const groups = new Map([[groupA.id, groupA], [groupB.id, groupB]]);
  expect(resolveGeneratedNodePlacement({ saved: { position: { x: 20, y: 20 }, parentId: groupA.id }, expectedGroup: groupB, groupById: groups, explicitlyUngrouped: true }).parentId).toBeNull();
  expect(resolveGeneratedNodePlacement({ saved: { position: { x: 20, y: 20 }, parentId: groupA.id, groupingIntent: 'explicit' }, expectedGroup: groupB, groupById: groups }).parentId).toBe(groupA.id);
});

test('legacy container artifacts require automatic-group evidence', () => {
  const artifact = { id: 'n:A', parentNode: groupA.id, data: { label: 'A' } };
  const ambiguous = { id: 'n:custom', parentNode: groupA.id, data: { label: 'Custom' } };
  const result = reconcileStoredManualNodes({ manualNodes: [artifact, ambiguous], autoGroupBoxes: [groupA] });
  expect(result.manualNodes).toEqual([ambiguous]);
  expect(result.prunedIds).toEqual(new Set(['n:A']));
});

test('legacy container artifacts are pruned even when saved inside the wrong group', () => {
  const misplacedArtifact = { id: 'n:A', parentNode: groupB.id, data: { label: 'A' } };
  const explicitManual = withDiagramNodeProvenance(
    { id: 'n:A', parentNode: groupB.id, data: { label: 'A' } },
    DIAGRAM_NODE_PROVENANCE.MANUAL
  );
  const result = reconcileStoredManualNodes({
    manualNodes: [misplacedArtifact, explicitManual],
    autoGroupBoxes: [groupA, groupB],
  });
  expect(result.manualNodes).toEqual([explicitManual]);
  expect(result.prunedIds).toEqual(new Set(['n:A']));
});

test('a second reconciliation (project reload) cannot restore a pruned artifact', () => {
  const artifact = withDiagramNodeProvenance({ id: 'n:Old', data: { label: 'Old' } }, DIAGRAM_NODE_PROVENANCE.GENERATED);
  const first = reconcileStoredManualNodes({ manualNodes: [artifact] });
  const reloaded = reconcileStoredManualNodes({ manualNodes: first.manualNodes });
  expect(reloaded.manualNodes).toEqual([]);
});
